### PR TITLE
Canonicalize CRAN links

### PR DESCRIPTION
**Pull request by katrinleinweber**
[CRAN asks to use the  URL variant](https://cran.r-project.org/doc/manuals/R-exts.html#Specifying-URLs) when linking to packages ;-) This PR results from a semi-automatic search-and-replace script and implements their suggestion.

### CODE REVIEW

**Comment by ASKurz** [comment]
I followed the link but I don’t understand what you’re recommending I do. Could you spell it out a bit?

**Comment by katrinleinweber** [comment]
I'm suggesting to use the link format that CRAN suggests (`package=…` instead of `web/packages/…`), see the `Files changed` tab ⬆️ ;-)

The force-push above was due to me rebasing onto your updated `master` after #25.

**Comment by ASKurz** [comment]
Finally got around to this. Thank you! This looks like it was major effort.

**Comment by katrinleinweber** [comment]
Modestly ;-) I had puzzled together [a script like this](https://gist.github.com/katrinleinweber/2c76d9f763f135b76b4440268603d862#file-clone-rm-dx-from-doi-sh-L30-L34) just with `s_web/packages_packages=_g` and other `BRANCH` name ;-)

**Pull request merged**
